services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: spms_postgres
    environment:
      POSTGRES_USER: spms_admin
      POSTGRES_PASSWORD: spms_password
      # Databases for other services will be created by Spring Boot / init scripts, 
      # but we can set a default one here or rely on init scripts.
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spms_admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: spms_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: spms_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: spms_admin
      RABBITMQ_DEFAULT_PASS: spms_password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
