server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/spms_users
    username: spms_admin
    password: spms_password

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
